baseURL = "/"
languageCode = "es-ES"
defaultContentLanguage = "es"
title = "La Mojaquera"

googleAnalytics = "UA-131728141-1"
enableRobotsTxt = true
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging#image-resizing
resampleFilter = "Linear"

# Default JPEG quality setting. Default is 75.
quality = 80

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
#anchor = "smart"
