# https://www.netlify.com/docs/netlify-toml-reference/
[build]
publish = "public"
command = "hugo -b $URL"

[context.deploy-preview]
command = "hugo --i18n-warnings -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_GOOGLEANALYTICS = "dev"

[context.branch-deploy]
command = "hugo --i18n-warnings --buildDrafts -b $DEPLOY_PRIME_URL"

[context.deploy-deploy.environment]
HUGO_GOOGLEANALYTICS = "dev"
